#!/usr/bin/env bash

# Loopa igenom varje frukt i listan
# "fruit" är en variabel som får ett nytt värde varje varv
for fruit in apple pear banana kiwi; do

    # Skriv ut det aktuella värdet på i och fruit
    echo "Yummy fruit $i: $fruit"

    # Öka värdet på i med 1
    ((i+=1))

# Avsluta loopen
done

echo "range based for loop"
# range based for loop (brace expansion)
for i in {1..5}; do
	echo "$i"
done


end=5
# doesn't give the range
for i in {1..$end}; do
	echo "$i"
done
 

#C - style for loop insteaf of having variable

for ((i=0; i<end; i++)); do
	echo "$((i*1))"
done











