#!/usr/bin/env bash

declare -A file_type
#Defines this being an associative array

mkdir -p assets
# -p = idempotent, can run multiple times without accidentally generating multiple dirs
touch assets/cool{1..5}.md assets/secret{1..3}.pdf assets/script

chmod +x assets/script
#makes this executable

mkdir -p assets/cool_dir

for f in assets/*; do
# can find all types of files in assets/	
	filename="${f#*/}"
	#to remove the assets/ prefix
	echo $filename
	if [[ -d "$f" ]]; then
	#if it's a directory, then...
		file_type["$filename"]="directory"
		#our ass. array uses file name as the index
	elif [[ -x "$f" ]]; then
	#if it's an exe., then...
		file_type["$filename"]="executable"
	else
	#if it's neither, then...
		file_type["$filename"]="regular file"
	fi
done

for f in "${!file_type[@]}"; do
	# to make it loop
	# @ = all keys in this ass. array
	echo "$f -> ${file_type[$f]}"
done
