#!/usr/bin/env bash



file_path="$1"

if [[ f "$file_path" ]]; then
	echo "File '$file_path' exists"
	if [[ ! -x "$file_path" ]]; then
		echo "File '$file_path' not executable"
	fi
else
	echo "File '$file_path' does not exist"
	exit 1
fi

echo "Program continues here ..."
