#!/usr/bin/env bash

## IFS - Internal field separator
#Default: separates space, tab, newline

while IFS= read -r filename; do
	if [[ -f "$filename" ]]; then
	echo "$filename is a file"
else
	echo "$filename not found"
fi
done
